import fs from "node:fs";
import path from "node:path";
import { marked } from "marked";
import { loadConfig, ROOT_DIR, type PipelineConfig } from "./config.js";
import { collectReports } from "./rss.js";
import type { ReportMeta } from "./types.js";

// Static site generator: builds dist/site/ for GitHub Pages.
//   /                     index of all reports
//   /reports/<slug>/      one page per report (permanent URL, spec §39)
//   /feed.xml, /index.json copied from public/

const esc = (s: string): string =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

function page(title: string, body: string, rootPrefix: string, config: PipelineConfig): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="alternate" type="application/rss+xml" title="${esc(config.siteTitle)}" href="${rootPrefix}feed.xml">
<style>
  :root { color-scheme: light dark; }
  body { max-width: 46rem; margin: 2rem auto; padding: 0 1rem;
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         line-height: 1.6; }
  a { color: #0969da; } @media (prefers-color-scheme: dark) { a { color: #58a6ff; } }
  table { border-collapse: collapse; display: block; overflow-x: auto; }
  th, td { border: 1px solid #8884; padding: 0.3rem 0.6rem; text-align: left; }
  code, pre { background: #8881; border-radius: 4px; }
  pre { padding: 0.8rem; overflow-x: auto; } code { padding: 0.1rem 0.3rem; }
  .meta { color: #888; font-size: 0.9rem; }
  .badge { display: inline-block; border: 1px solid #8886; border-radius: 999px;
           padding: 0 0.6rem; font-size: 0.8rem; margin-right: 0.3rem; }
  header nav { margin-bottom: 2rem; }
</style>
</head>
<body>
<header><nav><a href="${rootPrefix}">${esc(config.siteTitle)}</a> · <a href="${rootPrefix}feed.xml">RSS</a></nav></header>
${body}
<footer class="meta"><hr>Generated by <a href="https://github.com/gpwork4u/research-pipeline">research-pipeline</a>. Automated research — not investment advice.</footer>
</body>
</html>
`;
}

function indexBody(reports: ReportMeta[]): string {
  const items = reports
    .map(
      (r) => `<li>
  <span class="meta">${esc(r.date)}</span>
  <a href="reports/${esc(r.slug)}/">${esc(r.title)}</a><br>
  <span class="badge">${esc(r.research_type)}</span><span class="badge">${esc(r.verdict)}</span>
  ${r.topics.map((t) => `<span class="badge">${esc(t)}</span>`).join("")}
  <div class="meta">${esc(r.one_sentence_conclusion ?? "")}</div>
</li>`,
    )
    .join("\n");
  return `<h1>Research Reports</h1>\n<ul style="list-style:none;padding:0;display:grid;gap:1rem">${items}</ul>`;
}

export function buildSite(rootDir: string = ROOT_DIR): string {
  const config = loadConfig(rootDir);
  const outDir = path.join(rootDir, "dist", "site");
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  const reports = collectReports(rootDir);

  // Report pages at /reports/<slug>/ — strip front matter before rendering.
  for (const r of reports) {
    const md = fs.readFileSync(path.join(rootDir, r.path), "utf8");
    const body = md.replace(/^---\n[\s\S]*?\n---\n/, "");
    const html = marked.parse(body, { async: false });
    const meta = `<p class="meta">${esc(r.date)} · ${esc(r.research_type)} · verdict: ${esc(r.verdict)} · confidence: ${esc(r.confidence)}</p>`;
    const dir = path.join(outDir, "reports", r.slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, "index.html"),
      page(r.title, meta + html, "../../", config),
    );
  }

  fs.writeFileSync(path.join(outDir, "index.html"), page(config.siteTitle, indexBody(reports), "", config));

  // Feed + machine-readable index at the site root.
  for (const f of ["feed.xml", "index.json"]) {
    const src = path.join(rootDir, "public", f);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(outDir, f));
  }
  fs.writeFileSync(path.join(outDir, ".nojekyll"), "");

  console.log(`[site] built ${reports.length} report page(s) -> ${outDir}`);
  return outDir;
}

const isMain = process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]));
if (isMain) buildSite();
